### ISSUE TITLE
Needs update following Path of Glouphie 

### ISSUE THREAD

**Issue by OilyHands** [tcpowell/spirit-tree-menu#2]
![image](https://github.com/tcpowell/spirit-tree-menu/assets/32822218/c3a9d4b1-ce08-41f8-9a5b-342b057dc31d)

POH spirit tree in the menu doesn't fit. Cheers

**Comment by reecespieces** [comment]
Noticed the same thing, but you can actually still click on it right now. It's just below Farming Guild, but it's not visible.

**Comment by idle-user** [comment]
Ended up teleporting to wrong place
RIP my muscle memory.

**Comment by tcpowell** [comment]
This has been merged into the RL plugin hub (and should be future proof if any new teleports are added).
